name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libsdl2-dev
      run: sudo apt update && sudo apt install libsdl2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run rustfmt
      run: cargo fmt --all --check
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
